#!/usr/bin/env python3
"""
Generate ~/.local/state/Beyond All Reason/uikeys.txt with BAR's default
(legacy) keybinds converted from scancode (physical position) to keycode
(typed character) form, so Dvorak users press the key labeled with the
shortcut letter and BAR recognizes it.

Re-run after BAR updates to resync with upstream defaults.
"""
import re
import urllib.request
from pathlib import Path

BASE = "https://raw.githubusercontent.com/beyond-all-reason/Beyond-All-Reason/master/luaui/configs/hotkeys"
FILES = ["chat_and_ui_keys.txt", "num_keys.txt", "legacy_keys.txt"]

NAMED = {
    "sc_comma": ",",
    "sc_period": ".",
    "sc_slash": "/",
    "sc_semicolon": ";",
    "sc_apostrophe": "'",
    "sc_grave": "`",
    "sc_backslash": "\\",
    "sc_minus": "-",
    "sc_equals": "=",
    "sc_space": "space",
    "sc_return": "enter",
    "sc_tab": "tab",
    "sc_backspace": "backspace",
    "sc_escape": "esc",
}

def convert(line: str) -> str:
    for k, v in NAMED.items():
        line = re.sub(r"\b" + re.escape(k) + r"\b", lambda _, v=v: v, line)
    return re.sub(r"\bsc_(?=\S)", "", line)

def main():
    out = [
        "// Generated by scripts/bar-gen-uikeys.py",
        "// Scancode (sc_X) bindings converted to keycode so BAR shortcuts",
        "// match the typed character (Dvorak-friendly).",
        "unbindall",
        "",
    ]
    for name in FILES:
        with urllib.request.urlopen(f"{BASE}/{name}") as r:
            content = r.read().decode()
        out.append(f"// ==== from {name} ====")
        for raw in content.splitlines():
            if re.match(r"^\s*keyload\b", raw):
                continue
            out.append(convert(raw))
        out.append("")
    dest = Path.home() / ".local/state/Beyond All Reason/uikeys.txt"
    dest.write_text("\n".join(out))
    print(f"wrote {dest} ({len(out)} lines)")

if __name__ == "__main__":
    main()
