{ config, lib, pkgs, ... }:

{
  imports =
    [ # Include the results of the hardware scan.
      ./hardware-configuration.nix
    ];

  # Use the GRUB 2 boot loader.
  boot.loader.grub.enable = true;
  boot.loader.grub.device = "/dev/sda";
  #boot.loader.grub.efiSupport = true;
  #boot.loader.grub.efiInstallAsRemovable = true;
  #boot.loader.efi.efiSysMountPoint = "/boot/efi";
  # Define on which hard drive you want to install Grub.
  #boot.loader.grub.device = "/dev/sda"; # or "nodev" for efi only

  boot.tmp.cleanOnBoot = true;
  zramSwap.enable = true;
  networking.hostName = "general-server"; # Define your hostname.
  networking.nameservers = [ "8.8.8.8" "8.8.4.4" "2001:4860:4860::8888" ];

  # IPv6 configuration for Contabo VPS (Contabo uses /112 prefix)
  networking.interfaces.ens18.ipv6.addresses = [{
    address = "2a02:c207:2167:642::1";
    prefixLength = 112;
  }];
  networking.defaultGateway6 = {
    address = "fe80::1";
    interface = "ens18";
  };
  environment.etc = {
    "resolv.conf".text = "nameserver 8.8.8.8\nnameserver 8.8.4.4";
  };
  #networking.hostName = "vmi1670642";
  #networking.domain = "contaboserver.net";
  services.openssh = {
    enable = true;
    # require public key authentication for better security
    settings.PasswordAuthentication = false;
    settings.KbdInteractiveAuthentication = false;
    settings.X11Forwarding = false;
    settings.PermitRootLogin = "no";
    # SFTP-only chroot for the warpspeed POS backup user. Daily .db
    # snapshots land in /snapshots, litestream WAL frames land in
    # /litestream. No shell, no port-forwarding, no TCP tunnels.
    extraConfig = ''
      Match User warpspeed-backup
        ChrootDirectory /var/lib/warpspeed-backups
        ForceCommand internal-sftp
        AllowTcpForwarding no
        X11Forwarding no
        PermitTunnel no
        AllowAgentForwarding no
    '';
  };
  users.users.root.openssh.authorizedKeys.keys = [
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOvpuaWhiyWISrRYXtOpBLo6Fo/+NzZ0812RHlorSuNF mike.rosseel@gmail.com"
  ];
  users.users.mike.openssh.authorizedKeys.keys = [
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOvpuaWhiyWISrRYXtOpBLo6Fo/+NzZ0812RHlorSuNF mike.rosseel@gmail.com"
  ];

  # ── warpspeed POS backup receiver ────────────────────────────────────
  # The Astropolis contabo-vps runs litestream + a daily sqlite3 .backup
  # timer that both push here over SFTP. No shell, no read access outside
  # the chroot. Pubkey is the dedicated ed25519 key generated on the VPS
  # (see ~/dev/astropolis/nixos-cfg/modules/warpspeed-backup.nix).
  users.groups.warpspeed-backup = { };
  users.users.warpspeed-backup = {
    isSystemUser = true;
    group = "warpspeed-backup";
    # Home doubles as the SSH login dir. The chroot above pins us there.
    home = "/var/lib/warpspeed-backups";
    createHome = false;   # tmpfiles owns the dir tree (chroot needs root)
    shell = "${pkgs.shadow}/bin/nologin";
    openssh.authorizedKeys.keys = [
      # Dedicated ed25519 key on the contabo VPS. Generated by hand once
      # at /var/lib/warpspeed-backup-keys/id_ed25519 on the VPS — the
      # private half lives there only, never enters the nix store, never
      # crosses any wire. Rotate by regenerating on the VPS and pasting
      # the new .pub here.
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBkr8Tw0sVoHSsItY2ht/ZnoWGZAqznkH1TaTe+Pszy+ warpspeed-backup@ap-contabo-vps"
    ];
  };
  systemd.tmpfiles.rules = [
    # The chroot root MUST be root-owned and not group/world writable,
    # otherwise sshd refuses to chroot into it (silent log entry, opaque
    # client-side "Connection closed").
    "d /var/lib/warpspeed-backups            0755 root             root             - -"
    "d /var/lib/warpspeed-backups/snapshots  0750 warpspeed-backup warpspeed-backup - -"
    "d /var/lib/warpspeed-backups/litestream 0750 warpspeed-backup warpspeed-backup - -"
  ];

  # Pick only one of the below networking options.
  # networking.wireless.enable = true;  # Enables wireless support via wpa_supplicant.
  # networking.networkmanager.enable = true;  # Easiest to use and most distros use this by default.

  # Set your time zone.
  time.timeZone = "Europe/Amsterdam";

  # Configure network proxy if necessary
  # networking.proxy.default = "http://user:password@proxy:port/";
  # networking.proxy.noProxy = "127.0.0.1,localhost,internal.domain";

  # Select internationalisation properties.
  # i18n.defaultLocale = "en_US.UTF-8";
  # console = {
  #   font = "Lat2-Terminus16";
  #   keyMap = "us";
  #   useXkbConfig = true; # use xkb.options in tty.
  # };

  services.postfix = {
    settings = {
      master = {
        smtp = {
          args = [ "-o" "smtp_helo_timeout=15" ];
        };
      };
      main = {
        inet_protocols = "all";
      };
    };
  };

  # Enable the X11 windowing system.
  # services.xserver.enable = true;
  environment.systemPackages = with pkgs; [ gnumake gcc ];
  programs.zsh.enable = true;
  environment.shells = with pkgs; [ bash zsh ];
  users.groups.mike = {};
  users.users.mike = {
        home = "/home/mike";
        isNormalUser = true;
        group = "mike";
        extraGroups = [ "wheel" ];
        shell = pkgs.zsh;
        ignoreShellProgramCheck = true;
  };
  security.sudo.extraRules = [{
    users = [ "mike" ];
    commands = [
      { command = "/run/current-system/sw/bin/nix-store *"; options = [ "NOPASSWD" "SETENV" ]; }
      { command = "/nix/store/*/bin/nix-store *"; options = [ "NOPASSWD" "SETENV" ]; }
      { command = "/run/current-system/sw/bin/nix-env *"; options = [ "NOPASSWD" ]; }
      { command = "/nix/store/*/bin/switch-to-configuration *"; options = [ "NOPASSWD" ]; }
      { command = "/run/current-system/sw/bin/systemctl *"; options = [ "NOPASSWD" ]; }
    ];
  }];

  system.stateVersion = "23.11"; # Did you read the comment?

}
